[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200


remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Optional, make logs human friendly
[fuzz]
runs = 64

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
